# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newui3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(853, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.label_image = QtWidgets.QLabel(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.listWidget = QtWidgets.QListWidget(self.splitter_3)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_12.addWidget(self.splitter_3)
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.TrainNormalizecheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.TrainNormalizecheckBox.setObjectName("TrainNormalizecheckBox")
        self.horizontalLayout_7.addWidget(self.TrainNormalizecheckBox)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.TrainDatPushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.TrainDatPushButton.setObjectName("TrainDatPushButton")
        self.horizontalLayout_9.addWidget(self.TrainDatPushButton)
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_9.addWidget(self.checkBox)
        self.spinBox_dataskip = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_dataskip.setEnabled(False)
        self.spinBox_dataskip.setObjectName("spinBox_dataskip")
        self.horizontalLayout_9.addWidget(self.spinBox_dataskip)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.TrainLoadButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.TrainLoadButton.setEnabled(False)
        self.TrainLoadButton.setObjectName("TrainLoadButton")
        self.horizontalLayout_9.addWidget(self.TrainLoadButton)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.WorkPushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.WorkPushButton.setObjectName("WorkPushButton")
        self.horizontalLayout_2.addWidget(self.WorkPushButton)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_2.addWidget(self.checkBox_3)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox.setEnabled(False)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.WorkLoadButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.WorkLoadButton.setEnabled(False)
        self.WorkLoadButton.setObjectName("WorkLoadButton")
        self.horizontalLayout_2.addWidget(self.WorkLoadButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.comboBoxFunc = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBoxFunc.setObjectName("comboBoxFunc")
        self.comboBoxFunc.addItem("")
        self.comboBoxFunc.addItem("")
        self.comboBoxFunc.addItem("")
        self.comboBoxFunc.addItem("")
        self.comboBoxFunc.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBoxFunc)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox.setMinimum(0.01)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.layoutWidget3 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_centrain = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_centrain.setObjectName("radioButton_centrain")
        self.horizontalLayout_5.addWidget(self.radioButton_centrain)
        self.spinBox_centers = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_centers.setEnabled(False)
        self.spinBox_centers.setObjectName("spinBox_centers")
        self.horizontalLayout_5.addWidget(self.spinBox_centers)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_rand = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_rand.setObjectName("radioButton_rand")
        self.horizontalLayout_4.addWidget(self.radioButton_rand)
        self.spinBox_rand = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_rand.setEnabled(False)
        self.spinBox_rand.setMinimum(1)
        self.spinBox_rand.setMaximum(1000)
        self.spinBox_rand.setObjectName("spinBox_rand")
        self.horizontalLayout_4.addWidget(self.spinBox_rand)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_11.setEnabled(True)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.spinBox_equalcen = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_equalcen.setEnabled(False)
        self.spinBox_equalcen.setMinimum(1)
        self.spinBox_equalcen.setMaximum(1000)
        self.spinBox_equalcen.setObjectName("spinBox_equalcen")
        self.horizontalLayout_3.addWidget(self.spinBox_equalcen)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_10.setEnabled(True)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_8.addWidget(self.radioButton_2)
        self.TrainDatPushButton_2 = QtWidgets.QPushButton(self.layoutWidget3)
        self.TrainDatPushButton_2.setEnabled(False)
        self.TrainDatPushButton_2.setObjectName("TrainDatPushButton_2")
        self.horizontalLayout_8.addWidget(self.TrainDatPushButton_2)
        self.TrainLoadButton_2 = QtWidgets.QPushButton(self.layoutWidget3)
        self.TrainLoadButton_2.setEnabled(False)
        self.TrainLoadButton_2.setObjectName("TrainLoadButton_2")
        self.horizontalLayout_8.addWidget(self.TrainLoadButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.layoutWidget4 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget4)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.layoutWidget4)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout.addWidget(self.radioButton_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.layoutWidget5 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.splitter = QtWidgets.QSplitter(self.layoutWidget5)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.pushButton_fit = QtWidgets.QPushButton(self.splitter)
        self.pushButton_fit.setObjectName("pushButton_fit")
        self.layoutWidget6 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_saveweights = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_saveweights.sizePolicy().hasHeightForWidth())
        self.pushButton_saveweights.setSizePolicy(sizePolicy)
        self.pushButton_saveweights.setObjectName("pushButton_saveweights")
        self.horizontalLayout_10.addWidget(self.pushButton_saveweights)
        self.pushButton_loadweights = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_loadweights.sizePolicy().hasHeightForWidth())
        self.pushButton_loadweights.setSizePolicy(sizePolicy)
        self.pushButton_loadweights.setObjectName("pushButton_loadweights")
        self.horizontalLayout_10.addWidget(self.pushButton_loadweights)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.horizontalLayout_11.addWidget(self.splitter)
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.splitter_2 = QtWidgets.QSplitter(self.layoutWidget5)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.pushButton_predict = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_predict.setObjectName("pushButton_predict")
        self.checkBox_2 = QtWidgets.QCheckBox(self.splitter_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_11.addWidget(self.splitter_2)
        self.horizontalLayout_12.addWidget(self.splitter_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главное окно"))
        self.label_14.setText(_translate("MainWindow", "Нормализация"))
        self.TrainNormalizecheckBox.setText(_translate("MainWindow", "Нормализовать все данные в диапазоне"))
        self.comboBox.setItemText(0, _translate("MainWindow", "0, 1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "-1, 1"))
        self.label_3.setText(_translate("MainWindow", "Входные данные"))
        self.label.setText(_translate("MainWindow", "Обучающая выборка"))
        self.TrainDatPushButton.setText(_translate("MainWindow", "Выбрать"))
        self.checkBox.setText(_translate("MainWindow", "Использовать каждое"))
        self.label_4.setText(_translate("MainWindow", "значение"))
        self.TrainLoadButton.setText(_translate("MainWindow", "Загрузить"))
        self.label_2.setText(_translate("MainWindow", "Рабочая выборка"))
        self.WorkPushButton.setText(_translate("MainWindow", "Выбрать"))
        self.checkBox_3.setText(_translate("MainWindow", "Использовать каждое"))
        self.label_13.setText(_translate("MainWindow", "значение"))
        self.WorkLoadButton.setText(_translate("MainWindow", "Загрузить"))
        self.label_5.setText(_translate("MainWindow", "РБФ"))
        self.label_6.setText(_translate("MainWindow", "Функция"))
        self.comboBoxFunc.setCurrentText(_translate("MainWindow", "Гаусса"))
        self.comboBoxFunc.setItemText(0, _translate("MainWindow", "Гаусса"))
        self.comboBoxFunc.setItemText(1, _translate("MainWindow", "Лапласа"))
        self.comboBoxFunc.setItemText(2, _translate("MainWindow", "Коши"))
        self.comboBoxFunc.setItemText(3, _translate("MainWindow", "Кусочно-линейная"))
        self.comboBoxFunc.setItemText(4, _translate("MainWindow", "Вигнера"))
        self.label_7.setText(_translate("MainWindow", "Радиус"))
        self.label_8.setText(_translate("MainWindow", "Центры"))
        self.radioButton_centrain.setText(_translate("MainWindow", "Использовать каждое"))
        self.label_9.setText(_translate("MainWindow", "значение обучающей выборки"))
        self.radioButton_rand.setText(_translate("MainWindow", "Сгенерировать "))
        self.label_11.setText(_translate("MainWindow", "случайных значений в диапазоне выборки для каждого входа"))
        self.radioButton.setText(_translate("MainWindow", "Сгенерировать"))
        self.label_10.setText(_translate("MainWindow", "равноудаленных значений в диапазоне выборки для каждого входа"))
        self.radioButton_2.setText(_translate("MainWindow", "Загрузить из файла"))
        self.TrainDatPushButton_2.setText(_translate("MainWindow", "Выбрать"))
        self.TrainLoadButton_2.setText(_translate("MainWindow", "Загрузить"))
        self.label_12.setText(_translate("MainWindow", "Архитектура"))
        self.radioButton_3.setText(_translate("MainWindow", "Классическая"))
        self.radioButton_4.setText(_translate("Ma   inWindow", "Альтернативная"))
        self.pushButton_fit.setText(_translate("MainWindow", "Рассчитать весовые коэффициенты"))
        self.pushButton_saveweights.setText(_translate("MainWindow", "Сохранить"))
        self.pushButton_loadweights.setText(_translate("MainWindow", "Загрузить"))
        self.pushButton.setText(_translate("MainWindow", "Погрешность"))
        self.pushButton_predict.setText(_translate("MainWindow", "Рассчитать выходные значения"))
        self.checkBox_2.setText(_translate("MainWindow", "Денормализовать выходные значения"))

